"""
Trading signal model for the trading system.

This module defines the TradingSignal dataclass used to represent
trading signals generated by strategies.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import Optional
from logger import TradeEvent


@dataclass
class TradingSignal:
    """
    Represents a trading signal generated by a strategy.
    
    Attributes:
        symbol: Trading symbol (e.g., 'AAPL', 'BTCUSD')
        side: Order side ('BUY', 'SELL', 'HOLD')
        qty: Quantity to trade (optional, None for HOLD signals)
        strategy_id: Identifier of the strategy that generated this signal
        timestamp: Signal generation timestamp (UTC)
        price: Optional price at which signal was generated
        metadata: Optional dictionary for additional strategy-specific data
    """
    
    symbol: str
    side: str
    qty: Optional[float]
    strategy_id: str
    timestamp: datetime
    price: Optional[float] = None
    metadata: Optional[dict] = None
    
    def __post_init__(self) -> None:
        """Validate signal data after initialization."""
        if self.side not in ("BUY", "SELL", "HOLD"):
            raise ValueError(f"Invalid side: {self.side}. Must be BUY, SELL, or HOLD")
        
        if self.side in ("BUY", "SELL") and self.qty is None:
            raise ValueError(f"Quantity required for {self.side} signal")
        
        if self.qty is not None and self.qty <= 0:
            raise ValueError(f"Quantity must be positive, got {self.qty}")
    
    def __repr__(self) -> str:
        """Return string representation of signal."""
        qty_str = f"qty={self.qty}" if self.qty is not None else "qty=None"
        price_str = f", price={self.price:.2f}" if self.price is not None else ""
        return (
            f"TradingSignal(symbol='{self.symbol}', side='{self.side}', "
            f"{qty_str}{price_str}, strategy_id='{self.strategy_id}')"
        )
    
    def to_trade_event(self, event_type: str = "SIGNAL") -> TradeEvent:
        """Convert signal to TradeEvent for journaling."""
        return TradeEvent(
            symbol=self.symbol,
            side=self.side,
            qty=self.qty,
            price=getattr(self, "price", None),
            strategy_id=self.strategy_id,
            event_type=event_type,
            message=f"Signal generated by {self.strategy_id}",
        )
